name: Test Arduino Build

on: [push, pull_request]

jobs:
  build:
    name: Test compiling for esp8266
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncTCP
          ref: master
          path: CustomLibrary # must contain string "Custom"

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v2
        with:
          arduino-board-fqbn: esp8266:esp8266:nodemcuv2
          sketch-names: vmix-tally.ino
          platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          required-libraries: Adafruit NeoPixel,WiFiManager,WebSockets

      - name: Add artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vmix-tally.bin
          path: vmix-tally/build/esp8266.esp8266.nodemcuv2/vmix-tally.ino.bin

#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.github_token }}
#          file: vmix-tally/build/esp8266.esp8266.nodemcuv2/vmix-tally.ino.bin
#          asset_name: tally-${GITHUB_REF/refs\/tags\//}-esp8266-nodemcuv2.bin
#          tag: ${{ github.ref }}
#          overwrite: true
#        if: ${{ startsWith(github.ref, 'refs/tags/v') }}