name: Test App Build/Releasse

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Dependencies (Linux)
        run: sudo apt-get install libavahi-compat-libdnssd-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
        # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Install Dependencies (Windows)
        run: |
          msiexec /i 3thparty\bonjourcore2.msi /qn
          3thparty\bonjoursdksetup.exe /quiet
          Write-Output "::set-env name=BONJOUR_SDK_HOME::C:\Program Files\Bonjour SDK"
        if: matrix.os == 'windows-latest'

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.apple_key }}' > ~/private_keys/AuthKey_${{ secrets.apple_key_id }}.p8

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_root: ./app
          use_vue_cli: true
          skip_build: true
        env:
          API_KEY_ID: ${{ secrets.apple_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.apple_issuer_id }}
          BT_TOKEN: "${{secrets.bintray_apikey}}"

      - name: Cleanup artifacts
        if: matrix.os != 'windows-latest'
        run: |
          npx rimraf "dist_electron/!(*.exe|*.deb|*.rpm|*.AppImage|*.dmg|*.snap)"

      - name: Cleanup artifacts Win
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist_electron/!(*.exe)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist_electron