name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Dependencies (Linux)
        run: sudo apt-get install libavahi-compat-libdnssd-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Windows)
        run: |
          msiexec /i 3thparty\bonjourcore2.msi /qn
          3thparty\bonjoursdksetup.exe /quiet
          Write-Output "::set-env name=INCLUDE::C:\Program Files (x86)\Bonjour SDK;$env:INCLUDE"
        if: matrix.os == 'windows-latest'

      - name: Setup env (Windows)
        run: |
          dir "C:\Program Files (x86)\Bonjour SDK\Bin"
          dir "C:\Program Files"
          Write-Output "$env:INCLUDE"
        if: matrix.os == 'windows-latest'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          package_root: ./app

          use_vue_cli: true