name: Test Arduino Build

on: [push, pull_request]

jobs:
  build:
    name: Test compiling for esp8266
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v2
        with:
          arduino-board-fqbn: esp8266:esp8266:nodemcuv2
          sketch-names: vmix-tally.ino
          platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          required-libraries: Adafruit NeoPixel,WiFiManager,WebSockets

      - name: Upload artifacts
        run: |
          ls vmix-tally
